apiVersion: v1
kind: Service
metadata:
  name: app-svc-lb
  labels:
    app: application
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: application
  type: LoadBalancer


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - image: gcr.io/cicd-demo1/hello-docker:0
          imagePullPolicy: Always
          name: application
          ports:
            - containerPort: 8080
